apiVersion: v1
kind: PersistentVolume
metadata:
  name: h200-model-disk-a
  labels:
    serving-solutions/disk: model-0
spec:
  capacity:
    storage: 1500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: compute-csi-default-sc
  volumeMode: Filesystem
  csi:
    driver: compute.csi.nebius.com
    volumeHandle: <MODEL_DISK_A_HANDLE>
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: h200-model-disk-b
  labels:
    serving-solutions/disk: model-1
spec:
  capacity:
    storage: 1500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: compute-csi-default-sc
  volumeMode: Filesystem
  csi:
    driver: compute.csi.nebius.com
    volumeHandle: <MODEL_DISK_B_HANDLE>
