apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-0
  namespace: deepseek-v4-pro
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: compute-csi-default-sc
  volumeName: h200-model-disk-a
  resources:
    requests:
      storage: 1500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-1
  namespace: deepseek-v4-pro
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: compute-csi-default-sc
  volumeName: h200-model-disk-b
  resources:
    requests:
      storage: 1500Gi
