#!/usr/bin/env python3
"""Render tracks/nvidia-dynamo/observability: PodMonitors, PrometheusRules, a Grafana dashboard, a canary.

    python tools/render_observability.py

Metric names come from two sources: the worker Prometheus snapshots the harness captured
on the H200 site (tracks/nvidia-dynamo/studies/*/ARCHIVE-MANIFEST.sha256 lists them in the release archives:
sglang:* and dynamo_component_*), and Dynamo 1.4.0 source for frontend and router names
(lib/llm/src/http/service/metrics.rs, lib/runtime/src/metrics/prometheus_names.rs).
InfiniBand counters are node_exporter v1.9.1's infiniband collector; GPU metrics are DCGM's.
"""
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'tracks/nvidia-dynamo/observability'
HEADER = '# Generated by tools/render_observability.py — edit the generator, not this file.\n'

# SLO used by the burn-rate alerts. Example objectives (design guidance), per model.
SLO = {'nemotron-3-nano': {'ttft_p99_s': 2.0, 'itl_p99_s': 0.040},
       'deepseek-v4-pro': {'ttft_p99_s': 30.0, 'itl_p99_s': 0.060}}
PREFILL_MEMORY_RATIO = 0.70

RELABEL_DYNAMO_NAMESPACE = [  # the Planner filters on dynamo_namespace, which pods carry as a label
    {'sourceLabels': ['__meta_kubernetes_pod_label_nvidia_com_dynamo_namespace'], 'targetLabel': 'dynamo_namespace'},
    {'sourceLabels': ['__meta_kubernetes_pod_label_nvidia_com_dynamo_graph_deployment_name'], 'targetLabel': 'graph'},
    {'sourceLabels': ['__meta_kubernetes_pod_label_nvidia_com_dynamo_component_type'], 'targetLabel': 'component_type'},
    {'sourceLabels': ['__meta_kubernetes_namespace'], 'targetLabel': 'namespace'},
    {'sourceLabels': ['__meta_kubernetes_pod_name'], 'targetLabel': 'pod'},
]


def pod_monitor(name, types, port):
    return {'apiVersion': 'monitoring.coreos.com/v1', 'kind': 'PodMonitor',
            'metadata': {'name': name, 'namespace': 'monitoring', 'labels': {'release': 'prometheus'}},
            'spec': {'namespaceSelector': {'any': True},
                     'selector': {'matchExpressions': [
                         {'key': 'nvidia.com/dynamo-component-type', 'operator': 'In', 'values': types}]},
                     'podMetricsEndpoints': [{'port': port, 'path': '/metrics', 'interval': '15s',
                                              'relabelings': RELABEL_DYNAMO_NAMESPACE}]}}


def q99(metric, selector, window, by='graph'):
    return f'histogram_quantile(0.99, sum by ({by}, le) (rate({metric}_bucket{{{selector}}}[{window}])))'


def rules():
    alerts = []
    for graph, slo in SLO.items():
        for name, metric, target in (('TTFT', 'dynamo_frontend_time_to_first_token_seconds', slo['ttft_p99_s']),
                                     ('ITL', 'dynamo_frontend_inter_token_latency_seconds', slo['itl_p99_s'])):
            sel = f'graph="{graph}"'
            # Multi-window check: page on a fast burn (5m and 1h both above target),
            # ticket on a slow one (30m and 6h).
            for severity, short, long in (('page', '5m', '1h'), ('ticket', '30m', '6h')):
                expr = f'({q99(metric, sel, short)} > {target}) and ({q99(metric, sel, long)} > {target})'
                alerts.append({'alert': f'Dynamo{name}SloBurn', 'expr': expr, 'for': '2m',
                               'labels': {'severity': severity, 'graph': graph},
                               'annotations': {'summary': f'{graph}: p99 {name} above {target}s over {short} and {long}'}})
    alerts += [
        {'alert': 'DynamoNoWorkersRegistered',
         'expr': 'sum by (namespace) (dynamo_component_router_worker_registered) == 0', 'for': '5m',
         'labels': {'severity': 'page'},
         'annotations': {'summary': 'Frontend router has no registered workers; requests return 503',
                         'runbook': 'reference/troubleshooting.md#endpoint-returns-503-not-ready-while-every-pod-is-ready'}},
        {'alert': 'DynamoPrefillWorkersMissing',
         'expr': ('(sum by (namespace) (dynamo_component_router_worker_registered{worker_type="decode"}) > 0) unless '
                  '(sum by (namespace) (dynamo_component_router_worker_registered{worker_type="prefill"}) > 0)'),
         'for': '2m', 'labels': {'severity': 'page'},
         'annotations': {'summary': 'Decode workers registered but no prefill workers: the prefill router is deactivated',
                         'runbook': 'reference/troubleshooting.md#endpoint-returns-503-not-ready-while-every-pod-is-ready'}},
        {'alert': 'DynamoPrefillHostMemoryHigh',
         'expr': (f'max by (namespace, pod) (container_memory_working_set_bytes{{container="main", pod=~".+-prefill-.+"}}) / '
                  f'max by (namespace, pod) (kube_pod_container_resource_limits{{container="main", resource="memory", pod=~".+-prefill-.+"}})'
                  f' > {PREFILL_MEMORY_RATIO}'), 'for': '1m', 'labels': {'severity': 'page'},
         'annotations': {'summary': 'Prefill worker host memory above 70% of its limit (OOM risk; observed 308 GiB peaks)',
                         'runbook': 'reference/troubleshooting.md#prefill-pod-host-memory-swings-104--308-gib-and-is-oom-killed-at-384-gib'}},
        {'alert': 'DynamoKvTransferBootstrapSlow',
         'expr': 'histogram_quantile(0.99, sum by (namespace, le) (rate(sglang:kv_transfer_bootstrap_ms_bucket[5m]))) > 5000',
         'for': '10m', 'labels': {'severity': 'ticket'},
         'annotations': {'summary': 'NIXL bootstrap p99 above 5 s; check IB links and UCX devices'}},
        {'alert': 'DynamoPrefillBootstrapBacklog',
         'expr': 'max by (namespace, pod) (sglang:num_prefill_bootstrap_queue_reqs) > 32', 'for': '10m',
         'labels': {'severity': 'ticket'}, 'annotations': {'summary': 'Requests waiting for a KV transfer handshake'}},
        {'alert': 'DynamoQueueGrowing',
         'expr': 'max by (namespace, component_type) (sglang:num_queue_reqs) > 0 and deriv(max by (namespace, component_type) (sglang:num_queue_reqs)[15m:1m]) > 0',
         'for': '15m', 'labels': {'severity': 'ticket'},
         'annotations': {'summary': 'Worker queue growing for 15 minutes in one pool (prefill, decode or aggregated)'}},
        {'alert': 'DynamoKvPoolExhausted', 'expr': 'max by (namespace, pod) (sglang:token_usage) > 0.95', 'for': '10m',
         'labels': {'severity': 'ticket'}, 'annotations': {'summary': 'KV pool above 95%; retractions likely'}},
        {'alert': 'DynamoRequestsRetracted', 'expr': 'max by (namespace, pod) (sglang:num_retracted_reqs) > 0',
         'for': '5m', 'labels': {'severity': 'ticket'}, 'annotations': {'summary': 'Requests retracted for lack of KV space'}},
        {'alert': 'InfinibandPortErrors',
         'expr': ('sum by (instance, device, port) (increase(node_infiniband_port_errors_received_total[10m]) + '
                  'increase(node_infiniband_symbol_error_total[10m]) + increase(node_infiniband_link_downed_total[10m])) > 0'),
         'for': '0m', 'labels': {'severity': 'ticket'}, 'annotations': {'summary': 'InfiniBand errors or link-downs on a GPU node'}},
        {'alert': 'GpuXidError', 'expr': 'max by (Hostname, gpu) (DCGM_FI_DEV_XID_ERRORS) > 0', 'for': '0m',
         'labels': {'severity': 'page'}, 'annotations': {'summary': 'GPU reported an XID error'}},
        {'alert': 'DynamoCanaryFailing',
         'expr': 'max by (namespace) (kube_job_status_failed{job_name=~"inference-canary-.*"}) > 0', 'for': '10m',
         'labels': {'severity': 'page'}, 'annotations': {'summary': 'End-to-end chat completion through the gateway is failing'}},
    ]
    return {'apiVersion': 'monitoring.coreos.com/v1', 'kind': 'PrometheusRule',
            'metadata': {'name': 'dynamo-serving', 'namespace': 'monitoring', 'labels': {'release': 'prometheus'}},
            'spec': {'groups': [{'name': 'dynamo-serving', 'rules': alerts}]}}


def panel(pid, title, exprs, unit, y, x=0, w=12):
    return {'id': pid, 'type': 'timeseries', 'title': title, 'gridPos': {'h': 8, 'w': w, 'x': x, 'y': y},
            'datasource': {'type': 'prometheus', 'uid': '${datasource}'},
            'fieldConfig': {'defaults': {'unit': unit}, 'overrides': []},
            'targets': [{'expr': e, 'legendFormat': l, 'refId': chr(65 + i)} for i, (e, l) in enumerate(exprs)]}


def dashboard():
    g = 'graph=~"$graph"'
    rows = [
        ('TTFT (p50 / p99)', [(f'histogram_quantile(0.5, sum by (graph, le) (rate(dynamo_frontend_time_to_first_token_seconds_bucket{{{g}}}[5m])))', 'p50 {{graph}}'),
                              (f'histogram_quantile(0.99, sum by (graph, le) (rate(dynamo_frontend_time_to_first_token_seconds_bucket{{{g}}}[5m])))', 'p99 {{graph}}')], 's'),
        ('ITL (p50 / p99 / p99.9)', [(f'histogram_quantile({q}, sum by (graph, le) (rate(dynamo_frontend_inter_token_latency_seconds_bucket{{{g}}}[5m])))', f'p{float(q) * 100:g} {{{{graph}}}}') for q in ('0.5', '0.99', '0.999')], 's'),
        ('TPOT (mean, request duration / output tokens)', [(f'sum by (graph) (rate(dynamo_frontend_request_duration_seconds_sum{{{g}}}[5m])) / sum by (graph) (rate(dynamo_frontend_output_tokens_total{{{g}}}[5m]))', '{{graph}}')], 's'),
        ('Output tokens/s', [(f'sum by (graph) (rate(dynamo_frontend_output_tokens_total{{{g}}}[1m]))', '{{graph}}')], 'short'),
        ('Queue depth per pool', [(f'sum by (component_type) (sglang:num_queue_reqs{{{g}}})', 'queued {{component_type}}'),
                                  (f'sum by (component_type) (sglang:num_running_reqs{{{g}}})', 'running {{component_type}}'),
                                  (f'sum (dynamo_frontend_queued_requests{{{g}}})', 'frontend queued')], 'short'),
        ('KV usage and prefix hit rate', [(f'max by (pod) (sglang:token_usage{{{g}}})', 'KV usage {{pod}}'),
                                          (f'avg by (graph) (sglang:cache_hit_rate{{{g}}})', 'engine hit rate'),
                                          (f'avg by (graph) (dynamo_component_router_kv_hit_rate{{{g}}})', 'router predicted hit rate')], 'percentunit'),
        ('NIXL transfer (p99 latency, MB per request, GB/s)', [(f'histogram_quantile(0.99, sum by (le) (rate(sglang:kv_transfer_latency_ms_bucket{{{g}}}[5m])))', 'p99 latency ms'),
                                                              (f'histogram_quantile(0.5, sum by (le) (rate(sglang:kv_transfer_total_mb_bucket{{{g}}}[5m])))', 'p50 MB/request'),
                                                              (f'histogram_quantile(0.5, sum by (le) (rate(sglang:kv_transfer_speed_gb_s_bucket{{{g}}}[5m])))', 'p50 GB/s')], 'short'),
        ('Workers registered with the router', [('sum by (namespace, worker_type) (dynamo_component_router_worker_registered)', '{{namespace}} {{worker_type}}')], 'short'),
        ('InfiniBand bytes and errors', [('sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[1m]))', 'tx {{instance}}'),
                                         ('sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[1m]))', 'rx {{instance}}'),
                                         ('sum by (instance) (increase(node_infiniband_port_errors_received_total[5m]))', 'rx errors {{instance}}')], 'Bps'),
        ('GPU utilization, memory, XID (DCGM)', [('avg by (Hostname) (DCGM_FI_DEV_GPU_UTIL)', 'util {{Hostname}}'),
                                                 ('sum by (Hostname) (DCGM_FI_DEV_FB_USED) / sum by (Hostname) (DCGM_FI_DEV_FB_USED + DCGM_FI_DEV_FB_FREE) * 100', 'mem % {{Hostname}}'),
                                                 ('max by (Hostname) (DCGM_FI_DEV_XID_ERRORS)', 'XID {{Hostname}}')], 'short'),
        ('Prefill host memory vs limit', [('max by (pod) (container_memory_working_set_bytes{container="main", pod=~".+-prefill-.+"}) / max by (pod) (kube_pod_container_resource_limits{container="main", resource="memory", pod=~".+-prefill-.+"})', '{{pod}}')], 'percentunit'),
        ('Engine-side ITL p99 (SGLang histogram)', [(f'histogram_quantile(0.99, sum by (component_type, le) (rate(sglang:inter_token_latency_seconds_bucket{{{g}}}[5m])))', '{{component_type}}')], 's'),
    ]
    panels = [panel(i + 1, title, exprs, unit, (i // 2) * 8, (i % 2) * 12) for i, (title, exprs, unit) in enumerate(rows)]
    return {'title': 'Dynamo serving', 'uid': 'dynamo-serving', 'schemaVersion': 39, 'version': 1,
            'time': {'from': 'now-6h', 'to': 'now'}, 'refresh': '30s', 'tags': ['dynamo', 'llm-serving'],
            'templating': {'list': [
                {'name': 'datasource', 'type': 'datasource', 'query': 'prometheus'},
                {'name': 'graph', 'type': 'query', 'datasource': {'type': 'prometheus', 'uid': '${datasource}'},
                 'query': 'label_values(dynamo_frontend_requests_total, graph)', 'includeAll': True, 'multi': True}]},
            'panels': panels}


def canary(model):
    script = ('set -eu; curl -sf --max-time 120 https://$HOST/v1/chat/completions '
              '-H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" '
              f'-d \'{{"model":"$MODEL","messages":[{{"role":"user","content":"Reply with OK."}}],"max_tokens":4}}\' '
              '| grep -q completion_tokens')
    from tools.render_graphs import PROFILES
    return {'apiVersion': 'batch/v1', 'kind': 'CronJob', 'metadata': {'name': 'inference-canary', 'namespace': model},
            'spec': {'schedule': '*/5 * * * *', 'concurrencyPolicy': 'Forbid', 'failedJobsHistoryLimit': 3,
                     'successfulJobsHistoryLimit': 1, 'jobTemplate': {'spec': {'backoffLimit': 0, 'activeDeadlineSeconds': 180,
                     'template': {'metadata': {'labels': {'serving-solutions/role': 'canary'}},
                                  'spec': {'restartPolicy': 'Never', 'containers': [{
                                      'name': 'canary',
                                      'image': 'curlimages/curl:8.13.0@sha256:d43bdb28bae0be0998f3be83199bfb2b81e0a30b034b6d7586ce7e05de34c3fd',
                                      'command': ['sh', '-c', script],
                                      'env': [{'name': 'HOST', 'value': f'{model}.<INFERENCE_DOMAIN>'},
                                              {'name': 'MODEL', 'value': PROFILES[model]['model_id']},
                                              {'name': 'TOKEN', 'valueFrom': {'secretKeyRef': {'name': 'canary-token', 'key': 'token'}}}],
                                      'resources': {'requests': {'cpu': '50m', 'memory': '32Mi'}, 'limits': {'memory': '64Mi'}}}]}}}}}}


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    monitors = [pod_monitor('dynamo-frontend', ['frontend'], 'http'),
                pod_monitor('dynamo-workers', ['worker', 'prefill', 'decode'], 'system'),
                pod_monitor('dynamo-planner', ['planner'], 'metrics')]
    (OUT / 'podmonitors.yaml').write_text(HEADER + '\n---\n'.join(yaml.safe_dump(m, sort_keys=False) for m in monitors))
    (OUT / 'rules.yaml').write_text(HEADER + yaml.safe_dump(rules(), sort_keys=False, width=200))
    (OUT / 'dashboards').mkdir(exist_ok=True)
    (OUT / 'dashboards/dynamo-serving.json').write_text(json.dumps(dashboard(), indent=2) + '\n')
    (OUT / 'kustomization.yaml').write_text(HEADER + yaml.safe_dump({
        'apiVersion': 'kustomize.config.k8s.io/v1beta1', 'kind': 'Kustomization',
        'resources': ['podmonitors.yaml', 'rules.yaml'],
        'generatorOptions': {'disableNameSuffixHash': True, 'labels': {'grafana_dashboard': '1'}},
        'configMapGenerator': [{'name': 'dynamo-serving-dashboard', 'namespace': 'monitoring',
                                'files': ['dashboards/dynamo-serving.json']}]}, sort_keys=False))
    for model in SLO:
        d = OUT / 'canary' / model
        d.mkdir(parents=True, exist_ok=True)
        (d / 'canary.yaml').write_text(HEADER + yaml.safe_dump(canary(model), sort_keys=False, width=200))
        (d / 'kustomization.yaml').write_text(HEADER + yaml.safe_dump({
            'apiVersion': 'kustomize.config.k8s.io/v1beta1', 'kind': 'Kustomization', 'resources': ['canary.yaml']}))
    print('wrote', OUT)


if __name__ == '__main__':
    import sys
    sys.path.insert(0, str(ROOT))
    main()
