apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nemotron-3-nano
resources:
- ../as-measured/etcd
- ../as-measured/frontend-kv-router
- ../as-measured/workers-tp8-aggregated
- ../../../../../../../platform/sites/nebius-h200-2x8/storage/claims-nemotron-3-nano
components:
- ../common