apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nemotron-3-nano
resources:
- ../as-measured/benchmark-client-128k
- ../../../../../../../platform/sites/nebius-h200-2x8/storage/claims-nemotron-3-nano
components:
- ../common